CREATE DATABASE IF NOT EXISTS Aggregator;
Use Aggregator;

CREATE TABLE IF NOT EXISTS UserData (
	UserID INT NOT NULL AUTO_INCREMENT,
    Username VARCHAR(256) NOT NULL,
    Password VARCHAR(256) NOT NULL,
    DateCreated DATETIME NOT NULL,
    LastLogin DATETIME NULL,
    PRIMARY KEY(UserID)
);

CREATE TABLE IF NOT EXISTS Topic (
	TopicID INT NOT NULL AUTO_INCREMENT,
    TopicName VARCHAR(50),
    PRIMARY KEY(TopicID)
);

CREATE TABLE IF NOT EXISTS UserTopic (
	UserTopicID INT NOT NULL AUTO_INCREMENT,
    UserID INT NOT NULL,
    TopicID INT NOT NULL,
    PRIMARY KEY(UserTopicID),
    FOREIGN KEY (UserID) REFERENCES UserData (UserID),
    FOREIGN KEY (TopicID) REFERENCES Topic (TopicID)
);

CREATE TABLE IF NOT EXISTS Article (
	ArticleID INT NOT NULL AUTO_INCREMENT,
    ArticleTitle VARCHAR(256) NULL,
    ArticleAuthor VARCHAR(256) NULL,
    DatePublished DATETIME NULL,
    PRIMARY KEY (ArticleID)
);

CREATE TABLE IF NOT EXISTS UserArticle (
	UserArticleID INT NOT NULL AUTO_INCREMENT,
    UserID INT NOT NULL,
    ArticleID INT NOT NULL,
    IsSavedForLater BIT NOT NULL DEFAULT 0,
    IsFavorited BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (UserArticleID),
    FOREIGN KEY (UserID) REFERENCES UserData (UserID),
    FOREIGN KEY (ArticleID) REFERENCES Article (ArticleID)
);